### ISSUE TITLE
Using real slots provided instead of detected (HT) cores for BDII

### ISSUE THREAD

**Issue by kreczko** [htcondor/htcondor-ce#376]
Currently, the htcondor-ce-provider uses the query
```python
coll.query(htcondor.AdTypes.Startd, 'State=!="Owner"',
                              ['Arch', 'OpSys', 'OpSysMajorVer', 'OpSysName',
                               'DetectedCpus', 'DetectedMemory', 'Machine'])
```
(see https://github.com/htcondor/htcondor-ce/blob/master/contrib/bdii/htcondor-ce-provider#L190)
to collect information about the cluster - which is based on detected (HT) cores.

The [GridPP HTCondorCE docs](https://www.gridpp.ac.uk/wiki/Example_Build_of_an_HTCondor-CE_Cluster#Appendix_1_-_Fix_the_BDII_provider_to_use_real_slots_provided.2C_not_just_detected_CPUS) recommend a hack to replace `'State=!="Owner"'` with `'SlotTypeID == 1'` in order to use partitionable slots instead.

Would it be against the current concept to make that change in the main distribution? If not, I would be happy to provide a PR for this.

**Comment by brianhlin** [comment]
Hi @kreczko, I'm not sure that constraint would necessarily get you want you need since `SlotTypeID` is based on the slot types in the startd config and you could have more than one slot type. We could, however, update the query so that it only includes partitionable and static slots.

Are these core numbers supposed to indicate what is currently available in the cluster? If so, we can also make the `DetectedCpus` -> `TotalSlotCpus` change and make sure to ignore claimed slots.

**Comment by maxfischer2781** [comment]
We're indeed running multiple partitionable slots of different type on some worker nodes. So actually checking for all proper slots instead of just the first type is required in our case.

Other than that, it seem reasonable to test for the available slots, not the physical cores.

**Comment by kreczko** [comment]
> Are these core numbers supposed to indicate what is currently available in the cluster? If so, we can also make the `DetectedCpus` -> `TotalSlotCpus` change and make sure to ignore claimed slots.

Yes, `DETECTED_CPUS` might actually be better. We are trying to convey here how many cores are available for computing.
On most machines that's "cores excl. HT &leq; DETECTED_CPUS < cores including HT"

**Comment by brianhlin** [comment]
Hi @kreczko I finally got the chance to take a look at this and I'm a little confused by your last comment. I was suggesting that we we only gather information for the unused capacity in a pool, not total capacity by counting all the unclaimed slots. This would look something like this:

```
coll.query(htcondor.AdTypes.Startd,
           'State == "Unclaimed" && member(SlotType {"Partitionable", "Static"})',
           ['Arch', 'OpSys', 'OpSysMajorVer', 'OpSysName', 'Cpus', 'Memory', 'Machine'])
```

Moving to `Cpus` and `Memory` instead of `DetectedCpus` and `DetectedMemory` would ensure that we don't count all of the resources on a partitionable slot that have been carved off by dynamic slots.

If total capacity is the appropriate thing to count, then we should use the `Detected*` attributes and ignoring dynamic slots will fix any double-counting issues.

**Comment by kreczko** [comment]
> Moving to Cpus and Memory instead of DetectedCpus and DetectedMemory would ensure that we don't count all of the resources on a partitionable slot that have been carved off by dynamic slots.

But that's not what it is used in the BDII for. As far as I can tell the path is

`total_cores[classad['Machine']] = classad['DetectedCpus']` &rarr;
`total_cores=sum(total_cores.values())`  &rarr;
`GLUE2ComputingManagerTotalLogicalCPUs: {total_cores}`

Please correct me if I am wrong, but AFAIK `GLUE2ComputingManagerTotalLogicalCPUs`   should publish the total number of CPUs - regardless if they are used, e.g. by other slots.
From the spec: "Number of managed logical CPUs accessible via any of the available endpoints (a logical CPU corresponds to a CPU visible to the operating system)".

Since most of our nodes have HT, we usually set `DetectedCpus` manually, so it should correctly correspond to what we want to publish as (potentially) available.

Maybe it is my lack of understanding of the GridPP documentation that led to this issue and I don't think `State == "Unclaimed"` would return the correct numbers.

What we want to publish is the sum of all `DetectedCpus` in the cluster, regardless of partitioning, current use, or "Owner" claims. This is not a sum that should change unless we change the config or add/remove nodes.

**Comment by brianhlin** [comment]
Ok, this helps, thanks! If that's the case, I'm not sure there are any issues with the existing code because it only counts `DetectedCpus` once per machine in the total so your sum should only change *except* when a machine has been claimed by its [Owner](https://htcondor.readthedocs.io/en/latest/admin-manual/policy-configuration.html?highlight=owner%20state#owner-state). I could certainly remove this filtering but I can imagine cases where that'd be wrong, e.g. a pool that has nodes permanently in the `Owner` state.

**Comment by kreczko** [comment]
Indeed, the discussion here helped me to understand that. Maybe, because we set `DetectedCpus` at our side, the issue does not exist for us. OK, I am happy to close the issue, thanks for your time and explanations!

This is the transcript from the GridPP documentation:

### Appendix 1 - Fix the BDII provider to use real slots provided, not just detected CPUS
The BDII provider, `/var/lib/bdii/gip/provider/htcondor-ce-provider`, that comes with the system is a bit naive. It just says that if a node that has, say, 16 possible hyperthreads (cores * 2, what have you) then it must have 16 job slots on it. This is not so. Some of our 16 hyperthread nodes can only have max 12 jobs running, e.g. due to memory/

To fix this in a set-up like ours, with partitionable slots, a patch is used. At around line 129 of `/var/lib/bdii/gip/provider/htcondor-ce-provider`, change this constraint
```
'State=!="Owner"' 
```
to
```
'SlotTypeID == 1'. 
```
And, from line 129 to line 145, change all ‘DetectedCpus’ to ‘TotalSlotCpus’.

What does this mean? It means I’m counting up only the slots with `ID = 1`. This tells me the allocation, which the right logic for this job. And you will then get the right counts in the BDII output.
