### ISSUE TITLE
condor_ce_job_router_info to print ignored routes [Feature Reuquest]

### ISSUE THREAD

**Issue by thdesy** [htcondor/htcondor-ce#481]
if in a route the  `TargetUniverse` is not set/get's forgotten, the route is (reasonably) not shown by

```
condor_ce_job_router_info -config
```

for debugging it might be useful, if a short summery with all ignored routes could be printed as well or if an extra switch could be added.

**Comment by brianhlin** [comment]
Hi @thdesy, @johnkn would be the expert here but I believe that this is the case with HTCondor 9.0, at least if you're using Job Router transforms

**Comment by brianhlin** [comment]
@thdesy IIRC, you're running 9.0+ right now. Do you see the ignored routes data in `condor_ce_job_router_info -config`?

**Comment by thdesy** [comment]
@brianhlin sorry for not coming back (forgot about the request)

yes, we are now (mostly) on condor-9.0.4-1 & htcondor-ce-4.4.1-3

on a quick test, a test route without a target universe still does not show up in the router info

```
BROKENTESTROUTE @=end
[
 name = "BROKENTESTROUTE";
 Requirements = (x509UserProxyVOName =?= "nopevo");

 set_BROKENTESTROUTE =  True;
]
@end

JOB_ROUTER_ENTRIES = $(JOB_ROUTER_ENTRIES) $(BROKENTESTROUTE)
JOB_ROUTE_NAMES = $(JOB_ROUTE_NAMES) $(BROKENTESTROUTE)
```


```
> condor_ce_job_router_info -config  | grep BROKENTESTROUTE
> echo $?
1

> condor_ce_job_router_info -config  | grep DESYGRID
Name         : "DESYGRID"
	NAME DESYGRID
	# autoconversion of route 'DESYGRID' from new-classad syntax
	SET DESYGRIDSET true
```

**Comment by johnkn** [comment]
Is this the actual config? JOB_ROUTER_ROUTE_NAMES should be a list of names like this..


JOB_ROUTE_NAMES = $(JOB_ROUTE_NAMES) BROKENTESTROUTE


-tj

________________________________

**Comment by brianhlin** [comment]
Ah you're right. `condor_ce_job_router_info -config` will show well-formed, ignored routes, i.e. a properly formatted route that is not included in `JOB_ROUTER_ENTRIES`. We do try to catch malformed routes on startup of the `condor-ce` service, so you should see warnings in `journalctl -u condor-ce`. Alternatively, you can run the following:

```
CONDOR_CONFIG=/etc/condor-ce/condor_config /usr/share/condor-ce/verify_ce_config.py
```

We could think about making that first class and documenting its usage if that helps!

P.S. I wouldn't expect your example to work for a few other reasons: the list of routes should be defined by `JOB_ROUTER_ROUTE_NAMES` and its contents should be a list of route names (you've currently set it to the actual route classad). So something like this should work better instead of your last line, assuming that you add the `TargetUniverse` to the route:

```
JOB_ROUTER_ROUTE_NAMES = $(JOB_ROUTER_ROUTE_NAMES) BROKENTESTROUTE
```

**Comment by brianhlin** [comment]
@thdesy this looks solved to me so I'm going to go ahead and close this. Feel free to re-open it if you have any other questions!
